### ISSUE TITLE
secretsdump DRSUAPI "Connection reset by peer" on very large dumps

### ISSUE THREAD

**Issue by wintermute4316** [CoreSecurity/impacket#101]
When dumping hashes from a very large DC database using the drsuapi method the following error occurs after several thousand hashes have already been successfully been dumped.

[-] [Errno 104] Connection reset by peer
[\*] Something wen't wrong with the DRSUAPI approach. Try again with -use-vss parameter
[\*] Cleaning up...
[-] 'int' object has no attribute 'disconnectTree'
[*] Cleaning up...

The error states that the "connection was reset by peer", however the DC that I'm dumping from is fine and if I run again immediately after this error, it starts over again and then fails again in a different place on the list of hashes after many thousands (7k-10k) of hashes have been successfully dumped. Could this be a timeout issue and if so, can a timeout or retry option be added to allow for server side or DRSUAPI hiccups?

Also on a separate issue, when saving the data to disk using the -outputfile parm, if the dump is interrupted/fails in the middle by something like above, no hashes are saved to disk.  Seems that secretsdump won't save until all hashes have been dumped successfully, but would be better to save as you go.

I saw a previous post by Mubix that it would be great to resume on failure when a very large dump is occurring.  A resume would also help fix this issue.

**Comment by asolino** [comment]
Hey mate.. 

Thanks for the report. I indeed think there might be a timeout issue although we would need to investigate further. That `Connection reset by peer` is strange tho. Did you capture the traffic and verifier the target server closed the connection? If so, then there's gotta be something else making the server dropping the connection.

Now.. Indeed @mubix idea was great and I implemented it [here](https://github.com/CoreSecurity/impacket/commit/ae5b1dce67a3d3171b198b769fd89dc7b33892af) and [here](https://github.com/CoreSecurity/impacket/commit/18a3c42927dadeec90fc83dc55cfa8614b961fdb)
Looks like you didn't give it a try right maybe?

In fact, part of those changesets modified writining the output files as we were gathering the data, instead of waiting till finishing.

Please let me know if you can dump the target system with this resuming capability, then we can try to dig deeper on the first issue.

**Comment by wintermute4316** [comment]
Ah ok, I've been using the last release of 0.9.13 instead of the latest pull from the repository.  I'll give that a shot in a bit since I have a dump running currently using the vss method (that's more stable, but it tends to get caught and alerted on more often by defensive technologies since it creates services).

When I run the latest secretsdump, I'll startup a tcpdump to verify where the connection reset is coming from (if it occurs) but it still could be that something hiccups on the DC, the DC closes the drsuapi connection and in that case it would be nice to have a retry mechanism in secretsdump to re-establish another drsuapi bind and pick up where it left off (assuming it's not already there in this latest version or a resume).

I'll let you know how the next dump goes with the latest pull from github.  Thanks and btw awesome work with Impacket! It's a great set of tools.

**Comment by asolino** [comment]
Great.

Btw, I do not recommend mixing example scripts with older versions. If you use master's branch [secretsdump](https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py), use it with the master's branch [lib](https://github.com/CoreSecurity/impacket/tree/master/impacket). If you have 0.9.13, use this [secretsdump](https://github.com/CoreSecurity/impacket/blob/impacket_0_9_13/examples/secretsdump.py).

I'd say you should give it a try to the master branch, since several things got changed and improved.
Indeed the resume capability works that way, although you have to call the script again.
If for some reason the connection is dropped, you will see a `sessionresume_XXXXXXXX` (X = 8 random chars) in your current directory. Just call the secretsdump.py script again, with the same parameters, but specifying a new one `-resumefile` pointing to the previously saved resume file. 

Hope the VSS method works for you.. although it's prone to more failures. DRSUAPI is way more reliably (and faster ;) ).

Thanks for giving it a try! let me know how it goes..

**Comment by wintermute4316** [comment]
Splendid.  This new secretsdump's resumefile feature and write output as you go feature is much better.  So far I've had to resume three times and each time when restarting it's picked up where it left off (after waiting for about 3-5 minutes each time) with the appropriate session file each time.

What the pcap shows in Wireshark in each failure case is a SAMR "RidToSid request" where the DC takes just slightly longer than the client is willing to wait (about 5 seconds) for the expected SMB2 "Write response".  This causes the client to send a re-transmit and everything goes south from there resulting in the DC sending RST ACK's to the client to close the connection.  Before that problematic sequence of transmissions, everything is normal with several thousand sets of:

1. SAMR "RidToSid request" (client -> DC)
2. SMB2 "Write Response" (DC -> client)
3. SMB2 "Read Requst" (client -> DC)
4. SAMR "RidToSid response" (DC -> client)

So in the "Connection reset by peer" issues I'm seeing, it seems to be caused by a delay (just over 5 seconds) in the DC sending back the Write Response (in step 2) which causes the client to re-transmit step 1 again and it all goes bad from there leading to the failure.  When it's working, there is about a hundredth of a second between each of the above steps, but that 5 second delay on the part of the server causes the problem with the current code.  Maybe the server was busy at that moment.  Is there a way to adjust that 5 second timeout/re-transmit interval between step 1 and 2 of the communication to increase it?  I think if that timeout can be increased, preventing the re-transmit, that would fix this issue.

**Comment by asolino** [comment]
Great to know the resumefile feature worked for you. Did you test it with the latest commit I added? (https://github.com/CoreSecurity/impacket/commit/5842d99d7432df94f5adb006e09ab93485591d5e) .. Just wondering.. because it introduces a small change in the it handles the resume files.

Thanks very much for your analysis. Let me dig into the code to see if there's something related to your comments. The timeouts can be increased, but I'm wondering whether this is a re-transmition sent by impacket or by our client's OS. Does Wireshark give you a hint of it? Is that re-transmit happening at the TCP level or do you see a new SMB request for the RidToSid() call? (w/o Wireshark flagging it as a retransmition)

thanks!

**Comment by wintermute4316** [comment]
I pulled the master branch just before that commit, so I didn't get version.  On the other item, you're right that it's a TCP re-transmission.  Without putting to much detail here, see below for a simple sanitized break down of where the transmission fails.  Before packet 35000, everything was humming along fine.

No|Time|Src|Dst|Protocol|Length|Info
35000|454.335157|Client|DC|SAMR|230|RidToSid request
35001|459.364882|Client|DC|SAMR|230|[TCP Retransmission] RidToSid request
35002|459.365580|DC|Client|SMB2|150|Write Response
35003|459.365668|DC|Client|SMB2|150|[TCP Retransmission] Write Response
35004|459.365680|Client|DC|TCP|78|[ACK] Seq=1147962 Ack=1145071 Win=169472 Len=0
35005|459.378500|Client|DC|SMB2|183|Read Request
35006|459.378819|DC|Client|TCP|60|[RST, ACK] Seq=1145071 Ack=1147962 Win=0 Len=0

Packet 35001 is the first indication of the issue where it took over 5 seconds to get a response from the DC, so this causes the client to perform this TCP Retransmission.  As you can see from above, the Write Response did come from the DC (packet 35002), but it got there too late.  After looking at this some more, the packet that I think really threw the monkey wrench the communication is packet 35004 where it looks like the client requests a TCP window size adjustment and the server didn't like that and responds in packet 35006 where it sends a RST ACK.

Hopefully this helps.

**Comment by asolino** [comment]
Hey mate.. 

No worries.. that commit just made things easier (instead of changing the resumefile it will keep using the same one if the connection drops again). If you ever have time to test it I'd appreciate it.

Thanks again for your analysis. At first sight there's nothing much I could do from the library since those retransmissions are handled at the OS level. 

What is the client OS you are using? Anything in particular config about the network? Maybe trying from a different machine could give us a clue. I'm kind of lost here.

I'm running secretsdump against a DC running [clumsy](https://github.com/jagt/clumsy) setting up this way:
```
Lag: For inbound and outbound packets: 3000ms
Drop: 10% chance for inbound and outbound.
```

And so far so good (still dumping thru DRSUAPI.. it might take a while :p ).

Ideas welcomed..

**Comment by wintermute4316** [comment]
I'm using Kali 1.1 latest.  All communications are over an internal network, so it's more likely this is a function of the DC itself being taxed at that moment, not responding in time and then client re-transmissions and/or window size requests seem to break this communication.  Perhaps something can be done at a higher level in the communication (SMB?) to help it recover better when it hits this condition?  Not sure but thanks for taking a look at this.  btw, I'm on my 5th resume, but it still recovers each time and continues the dump, which is most excellent.  Resume was definitely a great feature add!

**Comment by asolino** [comment]
Adding controls at a higher level is a possibility but I'd like to be able to reproduce it somehow and/or understand whether this is a particular problem in the environment you're testing or something likely to happen.

I left running impacket testcases with a pretty scary `clumsy` set up and everything worked well. 
I will leave this issue open to see if somebody else has similar issues.

Great to know the resume capability helped you out!

**Comment by asolino** [comment]
Nobody else reported similar issues. Closing
