### ISSUE TITLE
Feature request - smbrelay default payload log & target list

### ISSUE THREAD

**Issue by Lexus89** [CoreSecurity/impacket#104]
The default payload for smbrelay is dumping the SAM hashes, right now we have functionality to log the challenge/responses to crack but a seperate log file for all the hashes could be very handy for a quick load-and-crack with JTR.

Also, from personal experience i have seen alot of SMBrelays originating from domain users with local admin privileges on all systems in a network. When the local admin hash (from the SAM dumped payload) is not shared between systems you need to switch smbrelay from one target to another manually. Implementing a load-a-list feature with IP's to relay, moving on from IP to next IP when auth&dump succeeded or failed(!) would provide us alot of ease. Ofcourse this means also keeping the user in mind, not switching to another IP already for example when a user auth is failed and another user later on would have worked. Every single user to every IP in the list maybe?

In this case the log file for local hashes should ofcourse also include the IP address of the system it was dumped from.

**Comment by mubix** [comment]
@Lexus89 check out #82 - looking for a proxy so you can choose your targets instead of just having a run through list ;-)

**Comment by Lexus89** [comment]
@mubix - Yes i know my comment is also there ;) I just wanted to create a separate topic due to the SAM log functionality and a bit different implementation than you requested (maybe abit easier, noticed author is quite busy)

**Comment by dirkjanm** [comment]
@asolino I've implemented a feature which adds support for a list of targets instead of a single host as target, which also includes recording state of which targets have been tried against which host.
I can provide this as a pull request, however I'm also working on some other features (such as transparent proxy support), which are making the file a bit long and hard to work with at the moment.

Would it maybe be a good idea to move smbrelayx out of the examples section and move it into a separate section (or even separate repo) relying on impacket? This way the classes can be organized better into files and for example separate directories for clients (think adding http, ldap clients) and servers.
Let me know your thoughts on this.

**Comment by asolino** [comment]
Hey @dirkjanm 

Thanks for your thoughts. Great to know you have been working on improving `smbrelayx.py`. I agree with you it is getting too big to be in a single file. I think in the long term we will end up taking it off the examples section, and probably changing its name (we're actually doing `ntlmrelay` rather than `smbrelay`). I need to better think about it (suggestions are welcomed).
In the meantime, if you need to reorganize the classes into different files, there's a hack already used by other examples (e.g. `psexec.py`) by having an examples directory inside the library (take a look at https://github.com/CoreSecurity/impacket/tree/master/impacket/examples) for extra files (original idea was to serve classes that are used by more than one example). 
It's definitely not the cleanest solution but we can have that luxury in a dev release until we better figure things out. Plus, I'd like to see what you're doing (and our dev users to test it!).

Let me know your thoughts now ;)

**Comment by dirkjanm** [comment]
@asolino yes I agree on the name change. Would it be fine with you if we moved smbrelayx to a separate folder in the examples, so for example /examples/smbrelayx/ or /examples/ntlmrelayx/?
Then we could have a subdirectory for clients and for servers. I hope that won't give too many problems.
If that's fine for you I can start restructuring my modifications a bit and try to get them more stable.

**Comment by asolino** [comment]
@dirkjanm Then only problem with that is when you install impacket.

Usually all examples go to `/usr/local/bin` and users would expect they can run the examples right away knowing `/usr/local/bin` is in the path. It'd be good if we keep it there. Then we can include classes located in sub folders for sure (that's why I proposed `impacket/examples`)

No problem at all you're giving.. it's just a matter of starting thinking how to grow this thing.. it's a good news ;). I'm torn towards taking all the examples out (just leave the basic ones) and create a different repro (say `impacket-utils`? proposals are welcomed everybody!) with `secretsdump`/`psexec`/`ntlmrelay`/etc.. I just liked the idea of installing a single thing with all included but we might have reached a moment where we'll have to change that.

Let's do this for the moment:
1. Create a `ntlmrelayx.py` and keep it in examples directory. Leave `smbrelayx.py` as it is and we will deprecate it later after code is more stable (so dev users can still play with both scripts).
2. Create a subdirectory in `impacket/examples/ntlmrelayx` and put all the extra classes there. Then from the script you can `from impacket.ntlmrelayx import classA, classB` kind of thing.

Then we will figure out how to continue moving the code.

Let me know if you're ok with this.

cheers

**Comment by byt3bl33d3r** [comment]
@dirkjanm if you need any help I'd be glad to! :D

**Comment by dirkjanm** [comment]
@byt3bl33d3r thanks for the offer :)
I'm quite far with the restructuring, the servers and clients are now separate and some utils are added that for example can read/automatically refresh a target list from a file.
I've also got a working concept of an LDAP and MSSQL relaying client, though they don't have any associated attacks yet, this is something that I'm still working on.
Once the code is in a stable enough state I'll start uploading it to the forked repo and then help on attacks, as well as adding new clients (a HTTP relay client would be nice) will be very welcome.
