### ISSUE TITLE
psexec processor architecture

### ISSUE THREAD

**Issue by hegusung** [CoreSecurity/impacket#110]
Hi,

I found a strange behavior with psexec

when I execute the command "echo %PROCESSOR_ARCHITECTURE% on a 64bit system I get the following answer :
x86

Is this a known issue and do you know how to solve it ?

thanks for your amasing job !

**Comment by asolino** [comment]
Hey there!

Yes.. it is a known issue because the target RemComSvc Windows Service runs as a 32-bit application, even if the target is a 64-bit OS. 

In order to solve this issue the RemComSvc service should also be compiled for 64-bit (don't know if this works) OSes and `psexec.py` should also detect the target version before picking the right executable to install the Windows Service (this should be easy).

Did you try the same with `wmiexec.py` instead of `psexec.py`?

**Comment by hegusung** [comment]
Thanks fo rthe answer,
everything works well with wmiexec.py, I will start to use this method. thanks !

**Comment by hegusung** [comment]
I might be willing to change the code in a near future, which method do you recommend to detect the target version ?

**Comment by asolino** [comment]
Hey @hegusung Sorry for the late response..

Best method I found over the years is trying to RPC Bind to an interface (e.g. port 135) using NDR64 transfer syntax. If not possible, it's a i386, otherwise x64.

**Comment by asolino** [comment]
Just in case @hegusung, here's the code for detecting the target architecture:
https://github.com/CoreSecurity/impacket/blob/master/examples/getArch.py

**Comment by hegusung** [comment]
Awesome thanks !
