### ISSUE TITLE
Error while parsing TGT ccache file

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#121]
Hello there,
I'm currently experiencing a weird bug around **using a TGT ccache file from impacket smbclient**.
The issue has already been detailed [here](https://github.com/gentilkiwi/kekeo/issues/1), it might interest you:

Cheers.

**Comment by asolino** [comment]
Hey there..

I agree 100% with @gentilkiwi here, great bug report indeed (so easy when there are clear repro steps!). Cheers for that.

Now,  with regards to `impacket smbclient`, I saw a few things that were not used the right way. You wrote using `smbclient` this way:

```
For ticket_not_replayable.ccache:

$ python smbclient.py -k -debug 192.168.11.136
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

[+] Using Kerberos Cache: /ticket_not_replayable.ccache
[+] No valid credentials found in cache. 
[-] invalid principal syntax 
```
A few things to consider here:
* You must specify a FQDN when using Kerberos authentication. Otherwise you will get a `KDC_ERR_S_PRINCIPAL_UNKNOWN` error. 
* Unlike `Samba's smbclient` you *need* to specify the `domain\username` information (otherwise it will try to connect anonymously). The reason is `impacket` will search inside the `ccache` file for tickets for the user you specify (instead of picking whatever is there first) and also to be consistent on how to specify an anonymous authentication. 
* When using ccache credentials, you might want to specify also `no-pass` switch, so you don't get asked for a password.

Please try testing this again the following way (I might have not understood your environment well, but hopefully you'll understand what I'm trying to do):
```
python smbclient.py -k -no-pass -debug ADYOLO.SWAG\Administrator@dc01.adyolo.swag
```

and let me know how it goes.

cheers!

**Comment by maaaaz** [comment]
Thank you @asolino for these _non-trivial_ information ! It might be worth to include them (or simply **insist**) somewhere in the impacket documentation or `smbclient.py` usage (yes it's there but it appears as positional optional arguments).

I'm almost making it but I now have `another general error` (documented in the kekeo issue), not related to smbclient but rather my kerberos setup. And again I failed to properly debug :) I'll try to investigate more soon:
```
root@kali:# python smbclient.py -k -no-pass -debug ADYOLO.SWAG/administrator@dc01.adyolo.swag
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

[+] Using Kerberos Cache: /root/test/Administrator@ADYOLO.SWAG.ccache
[+] Using TGT from cache
[+] Trying to connect to KDC at ADYOLO.SWAG
[-] Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)
```

Thanks !

**Comment by asolino** [comment]
Good to know it's working now @maaaaz. Impacket documentation is a big debt on my side to be honest. I'll think where is the best place to put an extra note about it.

Indeed I experienced the same error while playing with this issue. Problem seems to be the exported ticket does not have a session key set (actually, session key is set to '\x00'). Be sure to check, before running `sekurlsa::tickets` or `kerberos::list` that the TGT you want to export have the session key present.

I'm closing this issue since the `KRB_AP_ERR_BAD_INTEGRITY` issue doesn't seem to be related to a CCache parsing issue. Please open it up again if you think otherwise.

cheers!

**Comment by maaaaz** [comment]
@asolino, finally I figured it out: yes by default TGT's do not have a valid session key, that is a (new) protection.
So you need to set a specific registry key and then your TGT will be valid (check the kekeo issue).

I confirm that your smbclient works like a charm :D 
```
root@kali:# smbclient -k //dc01.adyolo.swag/c$ -d 3
lp_load_ex: refreshing parameters
Initialising global parameters
params.c:pm_process() - Processing configuration file "/etc/samba/smb.conf"
Processing section "[global]"
added interface eth0 ip=192.168.11.137 bcast=192.168.11.255 netmask=255.255.255.0
Client started (version 4.1.17-Debian).
Connecting to 192.168.11.136 at port 445
Doing spnego session setup (blob length=120)
got OID=1.3.6.1.4.1.311.2.2.30
got OID=1.2.840.48018.1.2.2
got OID=1.2.840.113554.1.2.2
got OID=1.2.840.113554.1.2.2.3
got OID=1.3.6.1.4.1.311.2.2.10
got principal=not_defined_in_RFC4178@please_ignore
cli_session_setup_spnego: using target hostname not SPNEGO principal
cli_session_setup_spnego: guessed server principal=cifs/dc01.adyolo.swag@ADYOLO.SWAG
Doing kerberos session setup
ads_cleanup_expired_creds: Ticket in ccache[FILE:/root/test/Administrator@ADYOLO.SWAG.ccache] expiration Thu, 24 Dec 2015 07:32:55 GMT
OS=[Windows Server 2012 R2 Datacenter Evaluation 9600] Server=[Windows Server 2012 R2 Datacenter Evaluation 6.3]
smb: \> ls
  $Recycle.Bin                      DHS        0  Sun Dec 20 19:08:26 2015
  Boot                              DHS        0  Tue Oct  1 01:02:40 2013

root@kali:# python smbclient.py -k -no-pass -debug ADYOLO.SWAG/administrator@dc01.adyolo.swag
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

[+] Using Kerberos Cache: /root/test/Administrator@ADYOLO.SWAG.ccache
[+] Using TGS from cache
Type help for list of commands
# use C$
# ls
drw-rw-rw-          0  Sun Dec 20 19:08:26 2015 $Recycle.Bin
drw-rw-rw-          0  Tue Oct  1 01:02:40 2013 Boot
```

**Comment by asolino** [comment]
Hey @maaaaz thanks for checking this!

cheers mate.
