### ISSUE TITLE
Reliably determine KDC host from /etc/krb5.conf or via SRV record

### ISSUE THREAD

**Issue by ropnop** [CoreSecurity/impacket#157]
Hey man -

I've been playing around with Kerberos and a Golden Ticket and ran into a few edge cases where tools like wmiexec will fail. I kept getting timeout errors and traced the problem with wireshark and a debugger.

For reference, I have a Golden Tickt tgt loaded into /tmp/krb5cc_0 and am trying to run the following:
```
python wmiexec.py -k -no-pass -debug host.domain.net
```
Basically the problem is it's not selecting the right KDC. In `krb5/kerberosv5.py ,sendRecieve()` if kdcHost is not present it falls back to trying to just looking up the host "DOMAIN.NET". In my small lab environment, this works because the A record for "DOMAIN.NET" is actually the Domain Controller (and therefore the KDC as well). But in this large environment I'm testing in, there are multiple DCs and multiple KDCs and the A records for DOMAIN.NET don't necessarily point to the them.

I can see two solutions to this, and wanted your input on what would be better/easier to implement:

* Look up the realm in the local /etc/krb5.conf to discover the KDC. This is how smbclient does it.
* Perform a SRV record lookup for _kerberos._tcp.domain.net to discover a valid KDC

I wrote a python snippet to get a KDC via SRV records:
```python
def getKDCName(domain):
        from dns import resolver
        answer = resolver.query('_kerberos._tcp.{}'.format(domain),'SRV')
        #just take the first record
        record = answer.response.additional[0].to_text()
        kdcHost = record.split(' ')[0]
        if kdcHost[-1] == '.':
            kdcHost = kdcHost[:-1]
        return kdcHost
```
At first I added this to kerberosv5.py, but ran into an issue where it doesn't reliably return the same KDC every time it's ran and can break when establishing a session because it does TGS requests to different servers. I thought about adding it to smbconnection.py to set an instance variable kdcHost, but pythondns has a name conflict with impacket.dns

I'm still learning the codebase and wanted to ask your opinion on where logic like this might fit in best. Could impacket.dns handle a SRV lookup like this (so we don't require pythondns)? What are your thoughts about seeing if /etc/krb5.conf exists and if the realm is defined there?

Thanks!

**Comment by asolino** [comment]
Hey @ropnop!

Thanks for digging into this.. some questions and comments:

> But in this large environment I'm testing in, there are multiple DCs and multiple KDCs and the A records for DOMAIN.NET don't necessarily point to the them.

I'm wondering where does it point to? Just curious.
If you hard code DOMAIN.NET in your /etc/hosts file pointing to the KDC you want, does it work?

> I can see two solutions to this, and wanted your input on what would be better/easier to implement:
>Look up the realm in the local /etc/krb5.conf to discover the KDC. This is how smbclient does it.

I wouldn't go this road since this won't be compatible under Windows environments.

> Perform a SRV record lookup for _kerberos._tcp.domain.net to discover a valid KDC

This could certainly work. Most probably in big environments you will get different targets due to round robin DNS

> At first I added this to kerberosv5.py, but ran into an issue where it doesn't reliably return the same KDC every time it's ran and can break when establishing a session because it does TGS requests to different servers.

Why would that be a problem?

cheers mate

**Comment by ropnop** [comment]
> I'm wondering where does it point to? Just curious.

I'm not entirely sure. There were about 14 A records and 8 answers to the SRV record. Every KDC was in there, but there were also other hosts that I couldn't reach. This might be a very atypical setup so it could just be a random edge case. I thought I was going crazy why wmiexec worked sometimes and timed out others, but it's because sometimes it would get the right KDC in the A request, and sometimes not.

> If you hard code DOMAIN.NET in your /etc/hosts file pointing to the KDC you want, does it work?

Ha! I can't believe I didn't think of that. Yes that works. I ended up just hardcoding the kdcHost in `kerberosv5.py, sendRecieve()`, but that would have been way easier :)

> Why would that be a problem?

So I actually just went through my wireshark capture. There's valid TGS requests to two different KDCs, and then it tries to connect to port 88 on a host it can't reach. So it actually looks like the all the KDCSs returned in the SRV record are not valid/reachable from the network I'm on. Sometimes it "gets lucky" and reaches KDCs for all requests, sometimes it doesn't and errors out. I have no idea what's going on in this network haha.

So here's two ways I think it could be addressed:

* Specify a KDC manually somewhere. Either command line argument, or environment variable?
* Perform the SRV lookup and attempt to connect to the first one. If it's successful, remember it for the rest of the connection process. If not, try the next one?

If we go with the SRV lookup, I'm assuming you'd want to do it natively instead of another DNS library. Where would that request make the most sense to happen and the kdcHost variable to be set? In the `smbconnection` instance?

Let me know how I can help. I can research how to natively do a SRV lookup within impacket.

**Comment by asolino** [comment]
> I thought I was going crazy why wmiexec worked sometimes and timed out others, but it's because sometimes it would get the right KDC in the A request, and sometimes not.

There's definitely something wrong on that domain. I doubt things work well there..

> Ha! I can't believe I didn't think of that. Yes that works. I ended up just hardcoding the kdcHost in kerberosv5.py, sendRecieve(), but that would have been way easier :)

Hehee.. Usually the simplest solution is in front of us and we look elsewhere.. it happens to us all :) .. Good to know it's working!

> Sometimes it "gets lucky" and reaches KDCs for all requests
As I said before.. unless I'm missing something.. that domain cannot work well.

Specifying the KDC manually is actually feasible, but not yet fully implemented in the library.

There are some scripts that you can specify the DC-IP/KDCHOST (it's actually the same) like [GetUserSPNs.py](https://github.com/CoreSecurity/impacket/blob/master/examples/GetUserSPNs.py) and [goldenPac.py](https://github.com/CoreSecurity/impacket/blob/master/examples/goldenPac.py). Parameter is `dc-ip`. If you check the [Kerberos](https://github.com/CoreSecurity/impacket/blob/master/impacket/krb5/kerberosv5.py) code you will find out the API is ready for that ( `kdcHost`, as you previously mentioned).

That works well at the `SMB` Layer but it does not at the `DCERPC` / `DCOM` layer.
The solution is not that complicated but must be carefully thought in order to not break backward compatibility.
 
Please open a separate issue requesting adding support for manually set kdcHost in DCERPC/DCOM and I'll tag it as an enhancement for the near future.

**Comment by asolino** [comment]
Fixed at https://github.com/CoreSecurity/impacket/issues/160
