### ISSUE TITLE
Improve NETBIOS_SESSION_PORT support

### ISSUE THREAD

**Issue by asolino** [CoreSecurity/impacket#172]
Based on https://github.com/CoreSecurity/impacket/pull/171 we should try to better support connections against port 139/tcp.

There are some issues needed to be solved first at the library level and then we can continue with the scripts.

**Comment by asolino** [comment]
Hey @real-datagram

Take a look at the changes make to `psexec.py`... you're welcome to start changing other scripts ;)

Let me know if it works on your side.

**Comment by real-datagram** [comment]
This doesn't work under Kali Linux 2.0 vs Windows 7 / 2012 hosts due to getRemoteName() returning a unicode string:

>   File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 668, in rawData
>     data = pack('!BBH',self.type,self.flags,self.length) + self._trailer
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 0: ordinal not in range(128)

Which causes the server in Pipes to remain an int and causes exceptions on input for server.writeFile.  I changed line 230 in psexec.py to fix, but it would disable UTF NB names:

`self.server = SMBConnection(self.transport.get_smb_connection().getRemoteName().encode('ascii','ignore'), self.transport.get_smb_connection().getRemoteHost(),`

Maybe running from Windows doesn't have this issue? Running this command:

> psexec.py -port 139 -target-ip 10.0.0.1 'DOMAIN/user:pass'@NBHOST

**Comment by asolino** [comment]
Hey @real-datagram thanks for verifying it.

Please re-test and let me know.

**Comment by asolino** [comment]
@real-datagram were you able to re-test?

**Comment by real-datagram** [comment]
Been sick, will check this week. Sorry for the delay!

**Comment by real-datagram** [comment]
@asolino confirmed working on my end

**Comment by asolino** [comment]
Thanks very much for checking it @real-datagram !

Closing..
