### ISSUE TITLE
ntlmrelayx.py requirements missing

### ISSUE THREAD

**Issue by blark** [CoreSecurity/impacket#183]
It seems that the ldap3 and ldapdomaindump requirements of ntlmrelayx.py didn't make it into the setup.py file. 

ntlmrelayx.py refuses to run without ldap3, and runs fine once you install it but dies when it tries to use `__import__` for ldapdomaindump. 

Do you want me to add them and make a pull request? 

Thanks

**Comment by asolino** [comment]
Hey @blark:

> It seems that the ldap3 and ldapdomaindump requirements of ntlmrelayx.py didn't make it into the setup.py file.

Yep you're right.. it is detailed in the [Readme](https://github.com/CoreSecurity/impacket/blob/master/README.md) tho:

_For some examples you will need pyOpenSSL (rdp_check.py) and ldap3 (ntlmrelayx.py)_

> Do you want me to add them and make a pull request?

 please do so! thanks very much!

**Comment by dirkjanm** [comment]
At the time I wrote the code ldapdomaindump was not yet on pip and/or fully tested, which is why it was added as an optional dependency (though required for relaying to LDAP). At the moment it is on PIP and in most cases it work fine, so it could/should be added to the Readme. Since installing ldapdomaindump also installs its commandline tools adding it in setup.py is maybe not something wanted for every impacket install, but that is up to @asolino :)

**Comment by asolino** [comment]
fixed in https://github.com/CoreSecurity/impacket/commit/54b5277d592895832d6f055179b15c0a617ac70b#diff-3b5f9fa7d91b1de733cf30dc041fcbf4
