### ISSUE TITLE
Escaping special characters

### ISSUE THREAD

**Issue by ankushgoel27** [CoreSecurity/impacket#198]
my password contains the special character "@". however none of the scripts if able to parse the target argument correctly and breaking. example, the smbexec and the wmiexec script breaks and splits the target at the first "@" character. I tried escaping with backslash, single quotes and double quotes, but nothing works.

**Comment by asolino** [comment]
hey @ankushgoel27. What impacket version are you using? Reason I'm asking is because this should be solved already, check for example this [line](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L305)

In the meantime, try not putting the password as command line parameter and it will be asked by the script. (e.g. Administrator@host)

**Comment by asolino** [comment]
Any news on this @ankushgoel27 ?

**Comment by asolino** [comment]
No answer, closing
