### ISSUE TITLE
[Enhancement] Secretsdump - list number of records

### ISSUE THREAD

**Issue by roo7break** [CoreSecurity/impacket#226]
It would be useful to know the total number of records that secretsdump will extract before actually extracting..

Maybe print on screen something like:

> [+] Total number of users: 12345

> [+] No. of active users: 12340

> [+] No. of disabled users: 5

**Comment by asolino** [comment]
Hey @roo7break 

That'd be awesome, but truth is you cannot know in advance the amount of users available (without going through each one of them, something undesired).
That is by designed decided by Microsoft. It actually makes sense, think about this scenario:
* There are 100k users, and you report there are 100k users
* You start processing them
* In between processing 1k more users are added
* What you reported was wrong.

That's why the RPC APIs provide a 'give me next user' kind of functionality, but never return the total amount.

If you find a workaround for this let me know.. this has been brought up in the past already.

Let me know if you have questions, if not please close this issue.

cheers!

**Comment by roo7break** [comment]
What if we are processing offline (LOCAL) files??

Thanks

Nikhil

**Comment by asolino** [comment]
> What if we are processing offline (LOCAL) files??

Even worse

When specifying DIT files, processing them takes a lot of time, keep in mind we're dealing with an undocumented format. Hence, in order to get the data about the amount of users before processing them, I would need to go over the whole DIT file, print the list of users, and then go back thru the DIT file again to process each one. That's likely to duplicated the amount of time it currently takes. Not an option sorry :s
