### ISSUE TITLE
smbConnection.logoff() doesn't close SMB session

### ISSUE THREAD

**Issue by t33m** [CoreSecurity/impacket#227]
You can find my [wmiexec.py](https://gist.github.com/tsma11/8077c92675be07e9ec79b549858456a8) with some debug changes, where I've tested smbConnection.logoff().

When I ran this code, I saw using netstat that connection to target tcp/445 port was not closed after smbConnection.logoff() was called.

I used Impacket v0.9.15 installed via pip.
Target machine - Windows Server 2012 R2 Standard.

Can you check it?

**Comment by tsma11** [comment]
also this issue can be test with [this](https://gist.github.com/tsma11/b282279577005dd837c3d9dfc8d71d17) simple code
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from time import sleep
from impacket.smbconnection import SMBConnection

hostname = '192.168.0.100'
username, password, domain = ['test', 'pass', 'domain']

smbConnection = SMBConnection(hostname, hostname)
smbConnection.login(username, password, domain)
smbConnection.logoff()

sleep(10)
print "Sleeping"
sleep(30)
```

**Comment by asolino** [comment]
Hey @tsma11 thanks for the report.

Indeed `smbConnection.logoff()` does not close the socket associated with the `SMBConnection`. That is actually on purpose. The reason lies by the fact that logging off from an existing SMBConnection doesn't mean the socket connection should be closed. We have implemented identities brute forcers that take advantage of this functionality, saving up all the TCP handshake when bruteforcing identities.

I do think however, we should programmatically provide a way to close the socket associated with a `SMBConnection`. We do have such functionality at the [SMB](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb.py#L2486) and [SMB3](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1587) but it is not at the `SMBConnection` one. I'll add it soon and then we can verify the scripts are correctly using it (they are not right now).

**Comment by tsma11** [comment]
Thanks for response @asolino, I will be wait.

**Comment by t33m** [comment]
@asolino, hi

Any updates?

**Comment by asolino** [comment]
Hey @t33m, not yet.. been swamped with other issues and work. Will try to address it soon.

**Comment by t33m** [comment]
Hi, @asolino, any news?

**Comment by asolino** [comment]
Hey @t33m, please check the latest commit and close the issue if it's working on your side.

**Comment by t33m** [comment]
Yes, @asolino, works fine for me.
Thank you!

**Comment by asolino** [comment]
Thanks to you @t33m!
