### ISSUE TITLE
ImportError: cannot import name dcerpc

### ISSUE THREAD

**Issue by llfrankiej** [CoreSecurity/impacket#228]
After installing impacket i always got following error when i want to run my script:

from impacket.dcerpc import dcerpc
ImportError: cannot import name dcerpc

I tried to reinstall impacket a few times, but i had no success.
I'm running Kali 2.0

**Comment by asolino** [comment]
Hey @llfrankiej 

`impacket.dcerpc` was deprecated long time ago and replaced with `impacket.dcerpc.v5`. If you have scripts using the old API you should install [impacket-0.9.13](https://github.com/CoreSecurity/impacket/releases/tag/impacket_0_9_13) which is the last version supporting that old interface. I wouldn't recommend it tho since you would loose a lot of new functionality.
