### ISSUE TITLE
Feature Request: added samrdump fields

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#237]
Would be nice to also have the password does not expire, account active, password last set, and logon script if possible in the SAMr

Also, CSV formatting would be awesome as well for easy grepping

**Comment by asolino** [comment]
Take a look at the commits @mubix.

I can make it output to a file instead of the screen, since it gets mixed with other output. Let me know what suits best for you or propose a different output.

Close the ticket whenever it's acceptable on your side.

PS: I don't really like this scripts output actually ;)

**Comment by mubix** [comment]
The CSV format is perfect and pretty easy to grep through. Good on my side. Closing Thanks!!
