### ISSUE TITLE
Implement missing client.connection and relevant tables for 'NT LM 0.12'.

### ISSUE THREAD

**Issue by contactr2m** [CoreSecurity/impacket#244]
It looks like 'NT LM 0.12' also maintains below tables:
Client.Connection
...
Client.Connection.OpenTable
...
Client.Connection.TreeConnectTable

[3.2.1.2 Per SMB Connection](https://msdn.microsoft.com/en-us/library/ee441477.aspx)
[3.2.1.4 Per Tree Connect](https://msdn.microsoft.com/en-us/library/ee442042.aspx)
Not sure if this should be marked as defect but there are places where client response is not properly handled due to these tables being missing.

for example:
[disconnect_tree](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb.py#L2775)

According to [3.2.5.30 Receiving an SMB_COM_TREE_DISCONNECT Response](https://msdn.microsoft.com/en-us/library/ee441927.aspx)
We have not completed handling of response:

- The Client MUST traverse the Client.Connection.OpenTable and remove all Opens for which the Client.Open.TreeConnect matches the TID in the request.

- The client MUST also traverse the Client.Connection.SearchOpenTable and release all SearchOpens for which the Client.SearchOpen.TreeConnect matches the TID in the request. 

- The client MUST also traverse the Client.Connection.TreeConnectTable and remove the TreeConnect for which the Client.TreeConnect matches the TID in the request.

**Comment by asolino** [comment]
Thanks for the report @contactr2m.

I can guarantee we're not following [MS-SMB2] strictly in terms of its functionality and requirements. However, we can add relevant items if necessary.

**Comment by martinuy** [comment]
Hi @contactr2m ,

As for SMBv1 (smb.py), we were not planning to add structures to track opened files and other objects specified by the standard. As @asolino said, it's not our goal to be exhaustive on the standard implementation so we prioritize changed based on our functional gain. Please also note that this protocol version is being deprecated and we are not focusing our efforts there. However, if you want to implement it yourself and send us a Pull Request, it's going to be welcomed :)

We will take your advice to clean opened files when doing tree disconnection in SMB3 (smb3.py).

As a final note, we encourage the use of SMBConnection that is a dialect-abstract layer for SMB communication (instead of using SMB or SMB3 classes directly).

**Comment by martinuy** [comment]
At 0ff281f00e2f563a8d5b68ef46ed375067d21fea:

 * We are now cleaning up open files from the corresponding session structure in SMB3 when disconnecting from a tree.

**Comment by contactr2m** [comment]
@martinuy Thanks. 👍 
I will see if i can implement that in my fork.  Yes, i do use SMBConnection only 💯 , i used lower level class just for demonstration purpose. :)
