### ISSUE TITLE
Feature Request: SMB/NTLM-relayx support for SMB2

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#282]
Nice to have feature that could help with the quickly evaporating SMB1 target dilemma ;-)

**Comment by asolino** [comment]
This is being developed in the context of [this](https://github.com/CoreSecurity/impacket/commits/relay-experimental) branch. In fact, it should actually be working. Testing welcomed ;)

**Comment by Gilks** [comment]
I was on an engagement recently where the client disabled SMB1 and SMB2.. Which was quite shocking to say the least. I was happy to discover this issue and see there's a dev branch for SMB2!

With that said, is it technically possible for ntlmrelayx to function with SMB3? If so, are there any known technical challenges that would come from developing a solution for SMB3?

**Comment by asolino** [comment]
Hey @Gilks. Shocking indeed!

Based on my understanding if should be technically possible to make it work in SMB3 except for dialect `3.1.1` due to the fact that after authentication it is enforced that the first Tree Connect must be signed from the client. But I'm not completely sure about `3.0` and `3.0.2`. More research is needed.
First thing that should be done it to add support for SMB3.x in the [smbserver.py](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbserver.py) that is used as a base for the relay stuff.

Btw.. just found this [interesting presentation](https://www.interopevents.com/uploads/1204250-SMB%203.1.1%20security%20in%20Windows%2010%20multichannel%20with%20pre-auth%20integrity.pdf) on SMB3 that could be useful.

Hope this helps,

**Comment by asolino** [comment]
Btw.. it now works in the following scenarios:

SMB/HTTP->SMB
SMB/HTTP->IMAP/S
SMB/HTTP->HTTP/S
SMB/HTTP->MSSQL
SMB/HTTP->SMTP

Where SMB can be SMBv1 or SMBv2. All with socks proxy available.
