### ISSUE TITLE
Error when uploading exe file to windows 2003: impacket.smb.UnsupportedFeature 

### ISSUE THREAD

**Issue by arv28** [CoreSecurity/impacket#288]
I'm using psexec.py to upload and install an executable file on windows from linux. An example would be 

> python psexec.py -c /root/utils/bin/wget.exe  username:password@host

This command succeeds for windows 2008 R2 and 2012 R2 but fails to upload the file on 2003 R2.
Here is the error for uploading to 2003 R2.

> Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies
> 
> [*] Trying protocol 445/SMB...
> [*] Requesting shares on 52.90.250.74.....
> [*] Found writable share C$
> [*] Uploading file QiVVUjjw.exe
> [*] Opening SVCManager on 52.90.250.74.....
> [*] Creating service JkrX on 52.90.250.74.....
> [*] Starting service JkrX.....
> [*] Uploading file wget.exe
> [-] Error uploading file wget.exe, aborting.....
> [*] Opening SVCManager on 52.90.250.74.....
> [-] Error performing the uninstallation, cleaning up
> Traceback (most recent call last):
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/bin/psexec.py", line 473, in <module>
>     executer.run(address)
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/bin/psexec.py", line 101, in run
>     self.doStuff(rpctransport)
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/bin/psexec.py", line 215, in doStuff
>     s.deleteFile(installService.getShare(), os.path.basename(self.__copyFile))
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/lib/python2.7/site-packages/impacket/smbconnection.py", line 564, in deleteFile
>     return self._SMBConnection.remove(shareName, pathName)
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/lib/python2.7/site-packages/impacket/smb.py", line 3910, in remove
>     self.list_path(service, path, password)
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/lib/python2.7/site-packages/impacket/smb.py", line 3785, in list_path
>     if resp.isValidAnswer(SMB.SMB_COM_TRANSACTION2):
>   File "/opt/race/share/sw/os/Linux_2.6_libc2.12_x86_64/python/lib/python2.7/site-packages/impacket/smb.py", line 714, in isValidAnswer
>     raise UnsupportedFeature, ("Unexpected answer from server: Got %d, Expected %d" % (self['Command'], cmd))
> impacket.smb.UnsupportedFeature: Unexpected answer from server: Got 117, Expected 50

What feature is not supported here?

**Comment by asolino** [comment]
Hey @arv28 

That unsupported feature exception has to do with the capability of handling different types of answers instead of the expected one. So, disregard that.

Now.. a few questions and request:
1. is that consistently happening every time you run `psexec.py` against the target? 
2. Did you try another remote execution scripts successfully? (`wmiexec.py`, `smbexec.py`, etc)
3. Can you try running impacket `0.9.16-dev`? There were many bugfixes since `0.9.15` was released.
4. Is there any chance to get a pcap capture of that original connection?

thanks

**Comment by arv28** [comment]
Hey @asolino 

I did try with `0.9.16-dev` and it seems to be working consistently across all windows platforms including 2003.

1. Yes happens consistently (on 0.9.15) only when `psexec.py` is run against Win 2003 target.
2. `wmiexec.py` worked fine with remote command execution on 2003 target. I didn't try `smbexec.py`. My use case is to upload and remote install an EXE file on windows in one go, instead of doing these separately. 

Is `0.9.16-dev` is a stable version? I'm planning to install this version in one our production environment.

Thanks for recommending the latest version.

**Comment by asolino** [comment]
Hey @arv28 

Great to know the latest version worked for you. 
With regards to your question, yes, I would go for `0.9.16-dev`. Especially for the `psexec.py` related features, there hasn't been many changes recently and it's working pretty well. 
I'll be tagging this release as stable soon, it's there already. I just need some time and finish some other features (related to SMB Relaying) that I'd like to have in this version.

Hope this helps,

**Comment by arv28** [comment]
Hey @asolino

Is there a way to upload a file and not execute the file on the target? I did see there is `smbclient.py` but not clear how to put this in a script to upload a file. Could you provide me with an example?

**Comment by asolino** [comment]
@arv28 

Many ways.. If you're inside `psexec.py` shell you can use `put` or `get` commands. Type `help` within the `psexec.py` shell and you'll get something like this:
```
C:\Windows>help

 lcd {path}                 - changes the current local directory to {path}
 exit                       - terminates the server process (and this session)
 put {src_file, dst_path}   - uploads a local file to the dst_path RELATIVE to the connected share (ADMIN$)
 get {file}                 - downloads pathname RELATIVE to the connected share (ADMIN$) to the current local dir 
 ! {cmd}                    - executes a local shell cmd


C:\Windows>
```
The important thing is that everything you upload/download is relative to the share used for communication ( Usually `ADMIN$` that points to `c:\windows` ).
`wmiexec.py` approach is way better since `put`/`get` commands aren't  share path independent. (click `help`  inside the `wmiexec.py` shell).

Another one is using `smbclient.py`. If you don't wanna play the interactive game.. you can create a file with the commands to execute and specify that as `smbclient.py`'s command line. E.g.

1. Create a `cmds.txt` file with
```
use c$
lcd /tmp
put myfile
exit
```
2. Execute `smbclient.py` and specify the `cmds.txt` file from the command line:
```
./smbclient.py -file cmds.txt user:password@targetHost
```
