### ISSUE TITLE
lookupsid.py not retrieving correct Domain SID

### ISSUE THREAD

**Issue by ropnop** [CoreSecurity/impacket#293]
Ran into this today while playing around.

lookupsid.py is not getting the correct Domain SID. It looks like it is only getting the local machine SID and is therefore only brute-forcing local accounts instead of domain SIDs.

I'm looking at the code, but unfortunately don't understand how it's querying the SID yet. This code looks like it's the culprit:

```python
        dce.bind(lsat.MSRPC_UUID_LSAT)
        resp = lsat.hLsarOpenPolicy2(dce, MAXIMUM_ALLOWED | lsat.POLICY_LOOKUP_NAMES)
        policyHandle = resp['PolicyHandle']

        resp = lsad.hLsarQueryInformationPolicy2(dce, policyHandle, lsad.POLICY_INFORMATION_CLASS.PolicyAccountDomainInformation)

        domainSid = resp['PolicyInformation']['PolicyAccountDomainInfo']['DomainSid'].formatCanonical()
```

It looks like it's using lsarpc, but when I perform an `lsaquery` using `rpcclient` I get the "correct" Domain SID.

For example, here's the resp that's returned in the code:

```
ipdb> resp['PolicyInformation']['PolicyAccountDomainInfo']['DomainSid'].formatCanonical()
'S-1-5-21-2318470451-3930354337-2673945738'
```

But this is the output from `rpcclient` against the same host with the same credentials:
```
root@kali:~# proxychains rpcclient -S off 10.9.122.5 -U "CSCOU\arizzo" -N -c "lsaquery"
ProxyChains-3.1 (http://proxychains.sf.net)
|S-chain|-<>-127.0.0.1:1080-<><>-10.9.122.5:445-<><>-OK
Domain Name: CSCOU
Domain Sid: S-1-5-21-1672938307-45828193-178384950
```

What method is lookupsid.py using to determine the Domain SID?

Let me know how I can help :)

**Comment by asolino** [comment]
Hey @ropnop 

Indeed `lookupsids.py` works only for local accounts. If you throw it against the DC, you'll get all the DC accounts ;).

Now, if you want that to happen also for the domain accounts, when targeting a domain member, you can easily change that, although, most probably the target (the domain member) host will forward your requests to the DC (I'm not completely sure about it but can be easily be checked by sniffing traffic).

All you have to do is to:
1. Change the information level when calling `hLsarQueryInformationPolicy2()` from `lsad.POLICY_INFORMATION_CLASS.PolicyAccountDomainInformation` to `lsad.POLICY_INFORMATION_CLASS.PolicyPrimaryDomainInformation`
2. The information level record is different.. so you will need to adjust that in this [line](https://github.com/CoreSecurity/impacket/blob/master/examples/lookupsid.py#L91). You can add a `resp.dump()` if you want to see what it looks like (all RPC structures support this method so you understand what's going on), but at the end, you have to change the line to:
```
domainSid = resp['PolicyInformation']['PolicyPrimaryDomainInfo']['Sid'].formatCanonical()
```
That should be it.. 

I did that script a while ago.. so I don't remember the details.. but something tells me I left it just for local accounts because if you ask domain SIDs it will forward the questions to the DC.. and that's something I could do directly.. I might be wrong tho.. worth researching..

have fun ;)

**Comment by asolino** [comment]
Oh.. and to answer your question:

> What method is lookupsid.py using to determine the Domain SID?

It uses [LsarQueryInformationPolicy2](https://msdn.microsoft.com/en-us/library/cc234321.aspx). Similar to what `rpcclient` uses.. although they use an older one [LsaQueryInformationPolicy](https://msdn.microsoft.com/en-us/library/cc234390.aspx). The trick is in the information class asked for.

**Comment by ropnop** [comment]
Thank you for the detailed response! Definitely helps me understand the code better. I'm gonna play around some more and make some modifications :)

**Comment by asolino** [comment]
Sure thing @ropnop.

It might makes sense to add that approach to `lookupsid.py` for those situations where you need to proxy the requests to the DC thru an already established connection to a domain joined machine (I recalled this all started when you had a SOCKS proxy to an already authenticated connection).

Everything's in here to create a pull request ;)

**Comment by ropnop** [comment]
You read my mind - that's exactly the use case I'm going for. Thanks!
