### ISSUE TITLE
ERROR_DS_NAME_ERROR_NOT_UNIQUE

### ISSUE THREAD

**Issue by aidandamerell** [CoreSecurity/impacket#320]
No user is being extracted using the "-just-dc-user" on a child domain.
E.G.
Parent domain: test.local
Child domain: secondary.test.local

Command: secretsdump.py secondary.test.local/administrator\:"**************"\@SDDC.secondary.test.local -just-dc-user "administrator"
Error returned is: ERROR_DS_NAME_ERROR_NOT_UNIQUE: Name translation: Input name mapped to more than one output name.

**Comment by asolino** [comment]
Hey @aidandamerell 

What impacket version are you using?

**Comment by asolino** [comment]
Hey again @aidandamerell 

Ok.. so that rang a bell but didn't know why.. Check [this](https://github.com/CoreSecurity/impacket/blob/master/impacket/examples/secretsdump.py#L2208) portion of code where the `-just-dc-user` is implemented.

Please recheck in the following way (assuming `secondary` is the NetBios name of the child domain):
```
secretsdump.py secondary.test.local/administrator:"**************"@SDDC.secondary.test.local -just-dc-user secondary/administrator
```
Let me know if it works on your side. I'm gonna add a warning message when this error is triggered.

**Comment by aidandamerell** [comment]
Hi @asolino,

I was using v0.9.16-dev. My bad - I assumed it was using the domain provided in the credential argument and not as part of the just-dc-user field.
Thanks for your help.

**Comment by asolino** [comment]
No worries @aidandamerell!

Actually that helped me adding that warning message :)

closing this one.
