### ISSUE TITLE
Ntlmrelayx forces encryption?

### ISSUE THREAD

**Issue by jamesbarlow** [CoreSecurity/impacket#332]
Hello,

There seems to be a bug when ntlmrelayx detects whether MSSQL encryption is required. Where the server does not require encryption, ntlmrelayx seems to mis-detect this, force encryption anyway and fails.

I must admin I'm not too familiar with the Impacket code, but the logic on lines 37/38 of impacket/examples/ntlmrelayx/clients/mssqlrelayclient.py doesn't seem quite right. It seems to test that the encryption flag is TDS_ENCRYPT_OFF, and then switches to TLS anyway.

`$ ./ntlmrelayx.py -t mssql://10.0.0.2 -i`
`Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies`
`[*] Running in relay mode to single host`
`[*] Config file parsed`
`[*] Setting up SMB Server`
`[*] Setting up HTTP Server`
`[*] Servers started, waiting for connections`
`[*] Incoming connection (10.0.0.1,56818)`
`[*] SMBD: Received connection from 10.0.0.1, attacking target 10.0.0.2`
`[*] Encryption required, switching to TLS`
`[-] Connection against target 10.0.0.2 FAILED`
`[-] [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]`
`[-] processRequest (0x73,[('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')])`
`[*] Handle: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]`
`[*] Closing down connection (10.0.0.1,56818)`
`[*] Remaining connections ['SMBRelay']`

Thanks!

**Comment by asolino** [comment]
Hey @jamesbarlow 

Thanks for your report.

The logic is somewhat confusing. Mainly due to the LOG message posted afterwards. But basically, the client switches to encryption either if it is enforced (`TDS_ENCRYPT_REQ`) or available but turned off (`TDS_ENCRYPT_OFF`). 
What's happening there is that `RC4` encryption algorithm is disabled at the server side. 
For some reason, I forgot to update `mssqlrelayclient.py` after this `tds.py` [commit](https://github.com/CoreSecurity/impacket/commit/754ee112). I will add this change right away so, if you have a chance to retest please let us know if it worked.

**Comment by asolino** [comment]
Hey @jamesbarlow 

Did you verify this?

**Comment by jamesbarlow** [comment]
That works here. Many thanks!
