### ISSUE TITLE
error using ipacket

### ISSUE THREAD

**Issue by wapik** [CoreSecurity/impacket#348]
File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 494, in calcUnpackSize
    return data.index('\x00')+1
ValueError: substring not found

Why get this error?

**Comment by crossmxn** [comment]
Im getting the same on latest Kali using trunk Impacket. Running "ntlmrelayx.py -tf list.txt".

**Comment by asolino** [comment]
Hey @wapik and @crossmxn 

Please `git pull` and test again. Let me know if it works on your side now.

**Comment by crossmxn** [comment]
It's working now @asolino thanks a lot :) :) btw, can you help me with 2 questions?

1- Whats the correct way to shut down ntlmrelayx? because Ctrl+C takes a lot of time and sometimes does not work
2- What are the possibilities when relaying non-admin users apart from using the -i flag to interact with the shares?

Thanks

**Comment by asolino** [comment]
Hey @crossmxn, welcomed!

> 1- Whats the correct way to shut down ntlmrelayx? because Ctrl+C takes a lot of time and sometimes does not work

For now, just hit `Ctrl-Z` to send it to the background and then `kill %1` (or whatever background process it is running). I should implement a cleaner way to finish the script. Feel free to create an Issue so we can track it.

> 2- What are the possibilities when relaying non-admin users apart from using the -i flag to interact with the shares?

You can use the `-socks` option. Instead of running something right away, for every relayed connection you will have a SOCKS proxy available. You can then use any tool you want that supports SOCKS and that matches the SMB Protocol. `proxychains` + `samba tools` is working quite well at the moment (impacket examples as well of course ;) ).
Here you have some screenshots on how to use it (https://twitter.com/ropnop/status/887819795680382980,  https://twitter.com/ropnop/status/887055850749276162 and https://twitter.com/agsolino/status/882622083913703428)

Feel free to ask.
