### ISSUE TITLE
smbexec "negotiate fail" 

### ISSUE THREAD

**Issue by jun0s** [CoreSecurity/impacket#350]
Hi @asolino 
with these changes.. https://github.com/CoreSecurity/impacket/commit/28f7c8a7cf46a2baaa38d6ec153840ffe03f05ab  smbexec.py it doesn´t work, i try with Windows Server 2008 standard SP2

me@PCME:~$ smbexec.py DOM/user@192.168.64.12 -debug
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[+] StringBinding ncacn_np:192.168.64.12[\pipe\svcctl]
[-] substring not found
me@PCME:~$

thank you so much!!!

**Comment by crossmxn** [comment]
ntlmrelayx also stopped working, doing a checkout to a previous commits fix the issue

**Comment by jun0s** [comment]
works!!! perfect.. thank you!

**Comment by crossmxn** [comment]
It's working now @asolino thanks a lot :) :) btw, can you help me with 2 questions?

1- Whats the correct way to shut down ntlmrelayx? because Ctrl+C takes a lot of time and sometimes does not work
2- What are the possibilities when relaying non-admin users apart from using the -i flag to interact with the shares?

Thanks
