### ISSUE TITLE
ntlmrelayx.py fail on PROTOCOL_CLIENT import

### ISSUE THREAD

**Issue by DanMcInerney** [CoreSecurity/impacket#401]
cmd: 
python2 ntlmrelayx.py -6 -wh Proxy-Service -of hashes/ntlmrelay-hashes -tf smb-signing-disabled-hosts.txt -wa 3

Errors out:
Traceback (most recent call last):
    File "submodules/impacket/examples/ntlmrelayx.py", line 487, in <module>
    from impacket.examples.ntlmrelayx.clients import PROTOCOL_CLIENTS

This commit is where the bug was introduced: 9f3c6e125ef7c763b894edb6cbd1b0875fb9fc25

**Comment by dirkjanm** [comment]
This is because of a change in the install method, which causes incompatible installations of impacket on the host.
You should make sure that your old version is fully removed before installing the new one. There are some instructions here:
https://github.com/CoreSecurity/impacket/issues/378#issuecomment-359545552

**Comment by asolino** [comment]
Hey @DanMcInerney.

Let us know if @dirkjanm comment solved your problem. In order to avoid the headaches with the install method change, I just [changed](https://github.com/CoreSecurity/impacket/commit/750b7b8945ceedab98e9e61bb1f0f70bfd39c571) impacket's dev version to `0.9.17-dev`. If you install impacket and the example scripts does not show that version, that means Python is picking an older version of the library.

**Comment by DanMcInerney** [comment]
Excellent thank you I'll try this out.

**Comment by DanMcInerney** [comment]
Yup, fixed.
