### ISSUE TITLE
Infinite loop in secretsdump.py while extracting domain hashes

### ISSUE THREAD

**Issue by jtesta** [CoreSecurity/impacket#413]
I used `secretsdump.py` to extract domain hashes from an `ntds.dit` file, and it consumed 100% CPU for over 12 hours until I killed it.  It extracted the same hashes thousands of times each.

I ran it with the following arguments:
```
python secretsdump.py -sam sam.reg -security security.reg -system system.reg -ntds ntds.dit LOCAL | tee ~/domain_hashes.txt
```

The output file contained over 700,000 lines, though only 650 are unique:
```
$ wc -l domain_hashes.txt 
728542 domain_hashes.txt
$ sort -u domain_hashes.txt > unique_hashes.txt
$ wc -l unique_hashes.txt 
653 unique_hashes.txt
```
User "John.Smith" has almost 2,200 entries, but it happens to be the same one over and over again:
```
$ grep John.Smith domain_hashes.txt | wc -l
2193
$ grep John.Smith domain_hashes.txt | sort -u | wc -l
1
```
Unfortunately, I ran into this on a production database during a pentest, so I can't share it to help debug.  I'd be happy to apply script diffs and report back what happens, though!

**Comment by jtesta** [comment]
I forgot to mention what version I was using: it was the master branch, pulled on March 27.

**Comment by asolino** [comment]
Hey @jtesta 

I heard about that bug before.. Keep in mind the offline dump relies on my Python implementation of the reverse engineering done by [Joachim Metz](http://forensic-proof.com/wp-content/uploads/2011/07/Extensible-Storage-Engine-ESE-Database-File-EDB-format.pdf) (Awesome work btw).
Of course there could be implementation bugs but still, have in mind there could be problems since it is an undocumented format.
I strongly recommend whenever possible to use the online mode that relies on [[MS-DRSR]](https://msdn.microsoft.com/en-us/library/cc228086.aspx)  AD replication functions.

I appreciate your willingness to help, but in order to fix this issue I really need a way to replicate the problem first. I've tried doing it remotely in the past but the process is pretty complex. Please have it in mind wherever you find the same problem and you can share the hives + DIT file.
