### ISSUE TITLE
wmiexec.py hange on StringBinding chosen

### ISSUE THREAD

**Issue by Kazatel** [CoreSecurity/impacket#463]
[user@host CORE]$ /opt/app/data/user/project/bin/wmiexec.py 'user:pass'@server.domain  hostname -debug
Impacket v0.9.17 - Copyright 2002-2018 Core Security Technologies

[+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
[*] SMBv3.0 dialect used
[+] Target system is server.domain and isFDQN is True
[+] StringBinding: \\\\server[\\PIPE\\atsvc]
[+] StringBinding: server[49154]
[+] StringBinding chosen: ncacn_ip_tcp:server.domain[49154]

after ctrl+c

^CTraceback (most recent call last):
  File "/opt/app/data/user/project/bin/wmiexec.py", line 90, in run
    self.shell = RemoteShell(self.__share, win32Process, smbConnection)
  File "/opt/app/data/user/project/bin/wmiexec.py", line 126, in __init__
    self.do_cd('\\')
  File "/opt/app/data/user/project/bin/wmiexec.py", line 201, in do_cd
    self.execute_remote('cd ' + s)
  File "/opt/app/data/user/project/bin/wmiexec.py", line 267, in execute_remote
    self.get_output()
  File "/opt/app/data/user/project/bin/wmiexec.py", line 248, in get_output
    self.__transferClient.getFile(self.__share, self.__output, output_callback)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/smbconnection.py", line 762, in getFile
    return self._SMBConnection.retr_file(shareName, pathName, callback)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/smb3.py", line 1529, in retrieveFile
    treeId = self.connectTree(shareName)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/smb3.py", line 864, in connectTree
    packet = self.recvSMB(packetID)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/smb3.py", line 383, in recvSMB
    data = self._NetBIOSSession.recv_packet(self._timeout)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/nmb.py", line 899, in recv_packet
    data = self.__read(timeout)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/nmb.py", line 977, in __read
    data = self.read_function(4, timeout)
  File "/opt/app/data/user/project/lib/python2.7/site-packages/impacket/nmb.py", line 959, in non_polling_read
    ready, _, _ = select.select([self._sock.fileno()], [], [], timeout)
KeyboardInterrupt
[-]

I am able to run wmic for this user remotely from my local PC under OS windows.

**Comment by mcnerneyd** [comment]
I'm having a similar issue.

The cause of my problem is that on the remote device the wmiexec is unable to create files in '\\127.0.0.1\ADMIN$' because, according to the remote device:

`C:\Users\Administrator>cmd.exe /Q /c cd \ 1> \\127.0.0.1\ADMIN$\abc.txt 2>&1`
`The name limit for the local computer network adapter card was exceeded.` 

The get_output method in wmiexec.py is failing on the getFile (because the file does not exist), and I'm getting this exception:
`SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)`

So far the best way I've found to get around this is to modify line 270 to read this instead:
`command += ' 1> ' + '%%SYSTEMROOT%%%s' % self.__output  + ' 2>&1'`

The while loop is continuing indefinitely, requiring you to ctrl-C the command.

Using the %SYSTEMROOT% location instead of the ADMIN$ share.

I would recommend that the following lines are added to the get_output exception handler:
`                elif str(e).find('STATUS_OBJECT_NAME_NOT_FOUND') >=0:`
`                    logging.error('Output transfer file does not exist')`
`                    return self.get_output()`

**Comment by Kazatel** [comment]
Hello, 

thank you very much for your guidance, you helped me figure out what is to root cause.  My user have just "Power-user" permission and it's not enough to create file inside "ADMIN$"  share.
After your post I went and created on E: drive new folder called "wmiexe_share" and let it share with read/write permissions for my User.
Then I tested if share is accessible \\127.0.0.1\wmiexe_share
As last I used "-share" parameter which is by default set to "ADMIN$" 

/opt/app/data/user/project/bin/wmiexec.py 'user:pass'@server.domain hostname -share wmiexe_share

Now all works fine.

PS:
if you don't need output on screen , just execute something , "-nooutput" parameter worked as well, without setting the share.

Once again , thank you very much for your help.

**Comment by Kazatel** [comment]
For Devs:
Thank you for great job here it . Looks like I am slowed a bit, but for anyone else like me, would be nice to have some error output instead of infinite loop, which tell them something like "don't have enough right to create file" or "file can't be created under share". So people could figure out what is wrong easily.
