### ISSUE TITLE
Using DCERPC's request() function (rpcrt.py) fails on package import

### ISSUE THREAD

**Issue by n3g** [CoreSecurity/impacket#74]
Hi,

I'm using the DCERPC's request function and my NDRCALL structure is defined in a package's __init__.py file, and not in a "normal" file.
When I use it like this, the request() function fails with:
IndexError: list index out of range

I traced the Exception to another, which is in the __import__ function:

TypeError: 'int' object does not support indexing

It seems to be an __import__ issue. So for example, if you define a package named "pack" and set a var in its __init__.py:

VAR="value"

and then try to import that package with import like this:

__import__('pack', globals(), locals(), -1)

you get:

TypeError: 'int' object does not support indexing

This seems to be the method used in this request() function and it fails if we try to import the package and not a specific file in the package.

Best regards,
Ricardo Oliveira

**Comment by asolino** [comment]
I'm sure it has to be something related with what the `request` method does:
```
    def request(self, request, uuid=None, checkError=True):
        [..]
        self.call(request.opnum, request, uuid)
        answer = self.recv()
        try:
            module = __import__(request.__module__.split('.')[-1], globals(), locals(), -1)
        except:
            # Try the subdirectories
            module = __import__('%s.%s' % (request.__module__.split('.')[-2],request.__module__.split('.')[-1]) , globals(), locals(), -1)
        respClass = getattr(module, request.__class__.__name__+'Response')
        [..]
        response =  respClass(answer, isNDR64 = isNDR64)
```
This method automatically casts the DCERPC answer to a structure that *must* be defined which is the request's class name + 'Response', so you don't have to do it manually. 
For example:
```
# 3.1.4.5.2 LsarEnumerateAccounts (Opnum 11)
class LsarEnumerateAccounts(NDRCALL):
    opnum = 11
    structure = (
       ('PolicyHandle', LSAPR_HANDLE),
       ('EnumerationContext',ULONG),
       ('PreferedMaximumLength',ULONG),
    )

class `(NDRCALL):
    structure = (
       ('EnumerationContext',ULONG),
       ('EnumerationBuffer',LSAPR_ACCOUNT_ENUM_BUFFER),
       ('ErrorCode', NTSTATUS),
    )
```
Whenever you do a request sending `LsarEnumerateAccounts` as parameter, you will get as the answer a `LsarEnumerateAccountsResponse` (or an Exception if there was an error) instead of just a string. That allows you to dump its contents (calling the `dump()` method) or to access the attributes as if it was a dictionary.

There must be something in your code or a bug in impacket that is triggering the error you're describing. There's at least another person that is developing a RPC Interface on a separate script and didn't have this issue tho. 
Why don't you show me your init.py? Maybe the problem's there.

**Comment by asolino** [comment]
No answer, closing.
