### ISSUE TITLE
Feature Request - SMBRelay Proxy 

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#82]
There is a more in-detail post here: https://room362.com/post/2014/2014-05-21-effective-ntlm-slash-smb-relaying/

But one of the features that I've never seen anywhere else is in a tool called ZackAttack, which is a SMB Relay. Here is how it works:
1. SMB or HTTP (NTLM) requests come in to a listener. This listener operates a few tricks to make the connections last longer and have multiple requests.
2. During this time a SOCKS proxy is set up and any request that comes through with the username of a known (currently being "relayed" / delayed, request, will have it's password rewritten) and relayed to whatever host the attacker wants. There are a few tricks in the relay that allows for even multiple use of one relayed source/victim's set of credentials. (I don't think it sends back an access denied, it does a try again or something (maybe a connection dropped?).

What this does for an attacker that isn't found in any other SMBRelay tool, is allows that attacker the versatility to target different hosts on the fly and based on username: So, if the attacker sees a relay connection coming in from a finance officer, the attacker can target a finance share (not psexec), and if they see a domain admin, can target the domain controller or something, but it's re-invigorates the SMB relay attack in a way that gives the attacker operational decision making. (vs the traditional target one host and give a lot of user's access denied answers - which is loud).

The final thing the tool does is store in a JTR format all of the challenge and requests that come in for cracking later.

**Comment by byt3bl33d3r** [comment]
@mubix I'm probably wrong , but isn't this what snarf does? https://github.com/purpleteam/snarf

**Comment by byt3bl33d3r** [comment]
@mubix I do see the value of having this functionality in a single python script though

**Comment by mubix** [comment]
I haven't used snarf since it came out but it wasn't really well suited for the use case above when I last used it.

**Comment by mubix** [comment]
Now I remember, it used a iptables redirect instead of proxy, which isn't as flexible during an operation as I'd like it. That, and NodeJS is a pain in the butt to install anywhere, and never gonna happen on target, whereas python will probably be there already.

**Comment by byt3bl33d3r** [comment]
well knowing @asolino he's probably already working on this :P if not though I'd love to take a crack at this myself,  would definitely be interesting to develop an extremely useful tool

**Comment by asolino** [comment]
Great idea to implement. @byt3bl33d3r I wish I was working on it already but I'm completely swamped these days and whenever I get to have some time I'd like to fix https://github.com/CoreSecurity/impacket/issues/78 first and then give it another crack at the [NDR](https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/ndr.py) runtime. There are still some padding issues there. 
So if you want to give it a try that'd be awesome!!. We need to research @mubix point 1. 'cause I don't know how it's done.
For point 2. I had noticed a while ago that if you sent `STATUS_SMB_BAD_UID`  from time to time (not on every packet) the client will send you the credentials back. So that could be a good trick to it. I left that behaviour [commented](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbserver.py#L4019) in the code.
Since we support `SMB2`, we should research whether that protocol would suit better than `SMB1` this trick we need.

**Comment by Lexus89** [comment]
To improve the do-more-with-your-auths would it perhaps be an idea (and quick win and more easy implementation for now) to also implement some form of target-hosts list from which IPs are read and relayed to, one at a time? So when a particular username fails at one host (for example when not being a local admin), the next time it will be relay to another target host from the list, and that for each different user account.

**Comment by mubix** [comment]
Updated link to blog post due to move in platform

@Lexus89 that would be awesome

**Comment by mubix** [comment]
bump ;-)

**Comment by Lexus89** [comment]
@mubix My colleague Dirk-Jan (participant on another thread here) is developing new functionality in coordination with asolino, he will check for this as well.

**Comment by asolino** [comment]
[This](https://github.com/CoreSecurity/impacket/commit/d285faf2eaa9d1bc74d9bd096a63e8d4b5756030) commit partially implements this feature request.

**Comment by asolino** [comment]
Closing this one.. [ntlmrelayx.py](https://github.com/CoreSecurity/impacket/blob/master/examples/ntlmrelayx.py) finally supports this functionality (and more)
