### ISSUE TITLE
Question/Feature request - Connection timeout option for DCOM connections

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#86]
hey man!
Is there a way to specify a timeout option when trying to connect to a host with a firewall that blocks RPC ports?

e.g I've got a Windows 10 box with a firewall,  when I try to run wmiquery.py for example:
```bash
#~ python wmiquery.py username:password@172.16.206.130
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

```
it just sits there forever trying to connect!

**Comment by byt3bl33d3r** [comment]
To clarify, a timeout option would be really useful if connecting to more hosts at once

**Comment by asolino** [comment]
Hmm.. forever is actually forever? ;)

In theory there's a timeout set when connecting to a DCOM interface [here](https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/dcomrt.py#L1246) that cannot be set. Try changing that value to see if is throws a timeout exception. If so, adding a method to set the timeout is super easy. If not, the problem is elsewhere.

I'll take a look at it whenever I have some time.

**Comment by byt3bl33d3r** [comment]
@asolino yep! that did the trick! I'll submit a PR later today! thanks again ;)
